# Elasticsearch
# 9200
#elasticsearch.ip=127.0.0.1
#elasticsearch.port=9300
#elasticsearch.pool=5
#elasticsearch.cluster.name=elasticsearch
elasticsearch:
  ip: 127.0.0.1
  port: 9300
  pool: 5
  cluster:
    name: elasticsearch
spring:
  port: 1212